"""Unified Skill subsystem (Learning Commit 3).

Skills are file-based artifacts under ``~/.stackowl/workspace/skills/<source>/<name>/``
with four origin sources:

- ``builtin/``   — shipped with StackOwl; read-only-by-agent.
- ``installed/`` — user-installed from external sources.
- ``user/``      — hand-written by the user.
- ``learned/``   — generated by the agent's SkillSynthesizerHandler.

Files are the source of truth; the ``skills`` index in SQLite is a cache for
fast lookup, semantic retrieval, and bookkeeping (success_rate, n_executions).
"""

from stackowl.skills.manifest import SkillManifest

__all__ = ["SkillManifest"]
