/**
 * StackOwl — Pellet Store
 *
 * Manages the storage and retrieval of "Pellets" — structured,
 * reusable knowledge artifacts generated by owls.
 *
 * Search is powered by a local BM25/TF-IDF engine — no external
 * embedding model required.  Works fully offline.
 */

import { join } from "node:path";
import {
  mkdir,
  readFile,
  writeFile,
  readdir,
  unlink,
  rename,
} from "node:fs/promises";
import { existsSync } from "node:fs";
import matter from "gray-matter";
import { TfIdfEngine } from "./tfidf.js";
import type { ModelProvider } from "../providers/base.js";
import {
  PelletDeduplicator,
  type DedupConfig,
  type DedupResult,
} from "./dedup.js";
import { PelletGraph } from "./graph.js";
import { log } from "../logger.js";

export type { DedupResult, DedupConfig };

export interface Pellet {
  id: string; // The filename (without .md)
  title: string;
  generatedAt: string;
  source: string;
  owls: string[];
  tags: string[];
  content: string; // The raw markdown body
  version: number;
  // ─── Dedup tracking fields (optional) ─────────────────────────
  /** ID of the pellet this one replaced */
  supersedes?: string;
  /** IDs of pellets that were merged into this one */
  mergedFrom?: string[];
  /** ISO timestamp of last merge */
  lastMergedAt?: string;
}

export class PelletStore {
  private pelletsDir: string;
  private tfidf: TfIdfEngine;
  private deduplicator: PelletDeduplicator;
  private graph: PelletGraph | null = null;

  /** In-memory cache for listAll() — avoids readdir + readFile on every search() call */
  private listAllCache: Pellet[] | null = null;
  private static readonly CACHE_TTL_MS = 30_000; // 30 seconds
  private cacheExpiresAt = 0;

  /**
   * @param workspacePath  Root workspace directory (pellets live in `<workspace>/pellets/`)
   * @param provider       Used for LLM-powered dedup merge decisions
   * @param dedupConfig    Dedup configuration overrides
   */
  constructor(
    workspacePath: string,
    provider?: ModelProvider,
    dedupConfig?: Partial<DedupConfig>,
  ) {
    this.pelletsDir = join(workspacePath, "pellets");
    this.tfidf = new TfIdfEngine(join(this.pelletsDir, "tfidf_index.json"));
    this.deduplicator = new PelletDeduplicator(
      this.tfidf,
      (id) => this.get(id),
      provider ?? undefined,
      dedupConfig,
    );
  }

  /** Expose deduplicator for bulk dedup operations */
  getDeduplicator(): PelletDeduplicator {
    return this.deduplicator;
  }

  /** Expose TF-IDF engine for graph building */
  getTfIdf(): TfIdfEngine {
    return this.tfidf;
  }

  /** Ensure the pellets directory exists and load the search index */
  async init(): Promise<void> {
    if (!existsSync(this.pelletsDir)) {
      await mkdir(this.pelletsDir, { recursive: true });
    }

    await this.tfidf.load();

    // Cold-start migration: if the TF-IDF index is empty but pellet files
    // exist on disk, rebuild the index from scratch.
    if (this.tfidf.isEmpty()) {
      const files = await readdir(this.pelletsDir).catch(() => [] as string[]);
      const mdFiles = files.filter((f) => f.endsWith(".md"));
      if (mdFiles.length > 0) {
        for (const file of mdFiles) {
          const id = file.replace(".md", "");
          const pellet = await this.get(id);
          if (pellet) {
            this.tfidf.addDocument(id, {
              title: pellet.title,
              tags: pellet.tags.join(" "),
              content: pellet.content,
            });
          }
        }
        await this.tfidf.persist();
      }
    }
  }

  /**
   * Save a pellet to disk with smart deduplication.
   *
   * Before writing, checks for semantically similar existing pellets.
   * The AI model decides whether to create, merge, supersede, or skip.
   *
   * @param opts.skipDedup  Bypass dedup for migrations/bulk imports/tests
   * @returns The dedup decision that was applied
   */
  async save(
    pellet: Pellet,
    opts?: { skipDedup?: boolean },
  ): Promise<DedupResult> {
    await this.init();

    // ─── Deduplication check ──────────────────────────────────────
    if (!opts?.skipDedup) {
      const decision = await this.deduplicator.evaluate(pellet);

      switch (decision.verdict) {
        case "SKIP":
          log.engine.info(
            `[PelletStore] SKIP: "${pellet.title.slice(0, 60)}" — ${decision.reasoning}`,
          );
          return decision;

        case "MERGE": {
          const existing = decision.targetPelletId
            ? await this.get(decision.targetPelletId)
            : null;
          if (existing) {
            // Update the existing pellet with merged content
            existing.content = decision.mergedContent || existing.content;
            existing.title = decision.mergedTitle || existing.title;
            existing.tags = decision.mergedTags || [
              ...new Set([...existing.tags, ...pellet.tags]),
            ];
            existing.owls = [...new Set([...existing.owls, ...pellet.owls])];
            existing.version = (existing.version || 1) + 1;
            existing.mergedFrom = [...(existing.mergedFrom || []), pellet.id];
            existing.lastMergedAt = new Date().toISOString();

            await this.writePellet(existing);
            log.engine.info(
              `[PelletStore] MERGE: "${pellet.title.slice(0, 50)}" → "${existing.id}" (v${existing.version})`,
            );
            return decision;
          }
          // Existing pellet gone — fall through to create
          break;
        }

        case "SUPERSEDE": {
          // Write new pellet with supersedes reference
          pellet.supersedes = decision.targetPelletId;
          await this.writePellet(pellet);

          // Delete the old pellet
          if (decision.targetPelletId) {
            await this.delete(decision.targetPelletId);
          }
          log.engine.info(
            `[PelletStore] SUPERSEDE: "${pellet.title.slice(0, 50)}" replaces "${decision.targetPelletId}"`,
          );
          return decision;
        }

        case "CREATE":
        default:
          // Fall through to normal write
          break;
      }
    }

    // ─── Normal write ─────────────────────────────────────────────
    await this.writePellet(pellet);
    return { verdict: "CREATE", reasoning: "new pellet" };
  }

  /**
   * Write a pellet to disk and update the TF-IDF index.
   * Internal method — use save() for the public API with dedup.
   */
  private async writePellet(pellet: Pellet): Promise<void> {
    const frontmatter: Record<string, unknown> = {
      title: pellet.title,
      generated_at: pellet.generatedAt,
      source: pellet.source,
      owls: pellet.owls,
      tags: pellet.tags,
      version: pellet.version,
    };

    // Include dedup tracking fields when present
    if (pellet.supersedes) frontmatter.supersedes = pellet.supersedes;
    if (pellet.mergedFrom?.length) frontmatter.merged_from = pellet.mergedFrom;
    if (pellet.lastMergedAt) frontmatter.last_merged_at = pellet.lastMergedAt;

    const raw = matter.stringify(pellet.content, frontmatter);
    const mdPath = join(this.pelletsDir, `${pellet.id}.tmp.md`);
    const finalPath = join(this.pelletsDir, `${pellet.id}.md`);

    // Write safely to tmp then rename
    try {
      await writeFile(mdPath, raw, "utf-8");
    } catch (err: any) {
      if (err.code === "ENOSPC") {
        throw new Error(`Disk full — cannot save pellet "${pellet.id}"`);
      }
      throw err;
    }
    try {
      await rename(mdPath, finalPath);
    } catch (err: any) {
      if (err.code === "ENOSPC") {
        throw new Error(`Disk full — cannot finalize pellet "${pellet.id}"`);
      }
      throw err;
    }

    // Invalidate the list cache so next search() picks up the new pellet
    this.listAllCache = null;

    // Update TF-IDF index (upsert — handles existing docs automatically)
    this.tfidf.addDocument(pellet.id, {
      title: pellet.title,
      tags: pellet.tags.join(" "),
      content: pellet.content,
    });
    await this.tfidf.persist();

    // Update graph incrementally if built
    if (this.graph?.isBuilt()) {
      this.graph.addPellet(pellet);
    }
  }

  /**
   * Read a specific pellet by ID.
   */
  async get(id: string): Promise<Pellet | null> {
    const mdPath = join(this.pelletsDir, `${id}.md`);
    if (!existsSync(mdPath)) return null;

    try {
      const raw = await readFile(mdPath, "utf-8");
      const { data, content } = matter(raw);

      const pellet: Pellet = {
        id,
        title: data.title || id,
        generatedAt: data.generated_at || new Date().toISOString(),
        source: data.source || "Unknown",
        owls: Array.isArray(data.owls) ? data.owls : [],
        tags: Array.isArray(data.tags) ? data.tags : [],
        version: data.version || 1,
        content: content.trim(),
      };

      // Dedup tracking fields (optional, backward-compatible)
      if (data.supersedes) pellet.supersedes = data.supersedes;
      if (Array.isArray(data.merged_from)) pellet.mergedFrom = data.merged_from;
      if (data.last_merged_at) pellet.lastMergedAt = data.last_merged_at;

      return pellet;
    } catch (error) {
      console.error(`[PelletStore] Failed to read pellet ${id}:`, error);
      return null;
    }
  }

  /**
   * List all available pellets.
   * Results are cached for 30 seconds — invalidated on save() or delete().
   */
  async listAll(): Promise<Pellet[]> {
    await this.init();

    // Return cached result if still fresh
    if (this.listAllCache && Date.now() < this.cacheExpiresAt) {
      return this.listAllCache;
    }

    try {
      const files = await readdir(this.pelletsDir);
      const pellets: Pellet[] = [];

      for (const file of files) {
        if (file.endsWith(".md")) {
          const id = file.replace(".md", "");
          const pellet = await this.get(id);
          if (pellet) pellets.push(pellet);
        }
      }

      // Sort by most recently generated
      const sorted = pellets.sort((a, b) => {
        return (
          new Date(b.generatedAt).getTime() - new Date(a.generatedAt).getTime()
        );
      });

      // Cache the result
      this.listAllCache = sorted;
      this.cacheExpiresAt = Date.now() + PelletStore.CACHE_TTL_MS;

      return sorted;
    } catch (error) {
      console.error("[PelletStore] Failed to list pellets:", error);
      return [];
    }
  }

  /**
   * Delete a pellet by ID and remove it from the search index.
   */
  async delete(id: string): Promise<boolean> {
    const mdPath = join(this.pelletsDir, `${id}.md`);
    if (existsSync(mdPath)) {
      await unlink(mdPath);
      this.listAllCache = null; // Invalidate cache
      this.tfidf.removeDocument(id);
      await this.tfidf.persist();

      // Update graph incrementally if built
      if (this.graph?.isBuilt()) {
        this.graph.removePellet(id);
      }
      return true;
    }
    return false;
  }

  /**
   * Search pellets by query using BM25-ranked TF-IDF.
   *
   * Returns pellets sorted by relevance — title matches and tag matches
   * are boosted above content matches.  No embedding model required.
   */
  async search(query: string): Promise<Pellet[]> {
    const all = await this.listAll();
    if (all.length === 0 || !query.trim()) return all;

    const results = this.tfidf.search(query);
    if (results.length === 0) return [];

    const pelletMap = new Map(all.map((p) => [p.id, p]));
    return results
      .map((r) => pelletMap.get(r.id))
      .filter((p): p is Pellet => p !== undefined);
  }

  // ─── Knowledge Graph Integration ────────────────────────────────

  /**
   * Build the in-memory knowledge graph linking pellets together.
   * Call once at startup; subsequent save/delete calls update it incrementally.
   */
  async buildGraph(): Promise<PelletGraph> {
    if (this.graph?.isBuilt()) return this.graph;

    this.graph = new PelletGraph(this, this.tfidf);
    await this.graph.build();
    return this.graph;
  }

  /**
   * Get the knowledge graph (builds it if not yet built).
   */
  async getGraph(): Promise<PelletGraph> {
    if (this.graph?.isBuilt()) return this.graph;
    return this.buildGraph();
  }

  /**
   * Find related pellets using graph traversal.
   * Falls back to BM25 search if graph is not built.
   */
  async findRelated(pelletId: string, limit = 10): Promise<Pellet[]> {
    if (!this.graph?.isBuilt()) {
      // Fallback: use BM25 search with pellet title
      const pellet = await this.get(pelletId);
      if (!pellet) return [];
      return this.search(pellet.title);
    }

    const related = this.graph.findRelated(pelletId, 2, limit);
    const pellets: Pellet[] = [];
    for (const r of related) {
      const pellet = await this.get(r.id);
      if (pellet) pellets.push(pellet);
    }
    return pellets;
  }

  /**
   * Search with graph-enhanced results — BM25 matches + their graph neighbors.
   */
  async searchWithGraph(query: string, limit = 15): Promise<Pellet[]> {
    if (!this.graph?.isBuilt()) {
      return this.search(query);
    }

    const graphResults = this.graph.findRelatedByQuery(query, limit);
    const pellets: Pellet[] = [];
    const seen = new Set<string>();

    for (const r of graphResults) {
      if (seen.has(r.id)) continue;
      seen.add(r.id);
      const pellet = await this.get(r.id);
      if (pellet) pellets.push(pellet);
    }
    return pellets;
  }
}
