/**
 * StackOwl — Pellet Store
 *
 * Manages the storage and retrieval of "Pellets" — structured,
 * reusable knowledge artifacts generated by owls.
 *
 * Search is powered by a local BM25/TF-IDF engine — no external
 * embedding model required.  Works fully offline.
 */

import { join } from "node:path";
import {
  mkdir,
  readFile,
  writeFile,
  readdir,
  unlink,
  rename,
} from "node:fs/promises";
import { existsSync } from "node:fs";
import matter from "gray-matter";
import { TfIdfEngine } from "./tfidf.js";

export interface Pellet {
  id: string; // The filename (without .md)
  title: string;
  generatedAt: string;
  source: string;
  owls: string[];
  tags: string[];
  content: string; // The raw markdown body
  version: number;
}

export class PelletStore {
  private pelletsDir: string;
  private tfidf: TfIdfEngine;

  /** In-memory cache for listAll() — avoids readdir + readFile on every search() call */
  private listAllCache: Pellet[] | null = null;
  private static readonly CACHE_TTL_MS = 30_000; // 30 seconds
  private cacheExpiresAt = 0;

  /**
   * @param workspacePath  Root workspace directory (pellets live in `<workspace>/pellets/`)
   * @param _provider      Kept for backward compatibility — no longer used for embeddings
   */
  constructor(workspacePath: string, _provider?: unknown) {
    this.pelletsDir = join(workspacePath, "pellets");
    this.tfidf = new TfIdfEngine(join(this.pelletsDir, "tfidf_index.json"));
  }

  /** Ensure the pellets directory exists and load the search index */
  async init(): Promise<void> {
    if (!existsSync(this.pelletsDir)) {
      await mkdir(this.pelletsDir, { recursive: true });
    }

    await this.tfidf.load();

    // Cold-start migration: if the TF-IDF index is empty but pellet files
    // exist on disk, rebuild the index from scratch.
    if (this.tfidf.isEmpty()) {
      const files = await readdir(this.pelletsDir).catch(() => [] as string[]);
      const mdFiles = files.filter((f) => f.endsWith(".md"));
      if (mdFiles.length > 0) {
        for (const file of mdFiles) {
          const id = file.replace(".md", "");
          const pellet = await this.get(id);
          if (pellet) {
            this.tfidf.addDocument(id, {
              title: pellet.title,
              tags: pellet.tags.join(" "),
              content: pellet.content,
            });
          }
        }
        await this.tfidf.persist();
      }
    }
  }

  /**
   * Save a pellet to disk and update the search index.
   */
  async save(pellet: Pellet): Promise<void> {
    await this.init();

    const frontmatter = {
      title: pellet.title,
      generated_at: pellet.generatedAt,
      source: pellet.source,
      owls: pellet.owls,
      tags: pellet.tags,
      version: pellet.version,
    };

    const raw = matter.stringify(pellet.content, frontmatter);
    const mdPath = join(this.pelletsDir, `${pellet.id}.tmp.md`);
    const finalPath = join(this.pelletsDir, `${pellet.id}.md`);

    // Write safely to tmp then rename
    await writeFile(mdPath, raw, "utf-8");
    await rename(mdPath, finalPath);

    // Invalidate the list cache so next search() picks up the new pellet
    this.listAllCache = null;

    // Update TF-IDF index (upsert — handles existing docs automatically)
    this.tfidf.addDocument(pellet.id, {
      title: pellet.title,
      tags: pellet.tags.join(" "),
      content: pellet.content,
    });
    await this.tfidf.persist();
  }

  /**
   * Read a specific pellet by ID.
   */
  async get(id: string): Promise<Pellet | null> {
    const mdPath = join(this.pelletsDir, `${id}.md`);
    if (!existsSync(mdPath)) return null;

    try {
      const raw = await readFile(mdPath, "utf-8");
      const { data, content } = matter(raw);

      return {
        id,
        title: data.title || id,
        generatedAt: data.generated_at || new Date().toISOString(),
        source: data.source || "Unknown",
        owls: Array.isArray(data.owls) ? data.owls : [],
        tags: Array.isArray(data.tags) ? data.tags : [],
        version: data.version || 1,
        content: content.trim(),
      };
    } catch (error) {
      console.error(`[PelletStore] Failed to read pellet ${id}:`, error);
      return null;
    }
  }

  /**
   * List all available pellets.
   * Results are cached for 30 seconds — invalidated on save() or delete().
   */
  async listAll(): Promise<Pellet[]> {
    await this.init();

    // Return cached result if still fresh
    if (this.listAllCache && Date.now() < this.cacheExpiresAt) {
      return this.listAllCache;
    }

    try {
      const files = await readdir(this.pelletsDir);
      const pellets: Pellet[] = [];

      for (const file of files) {
        if (file.endsWith(".md")) {
          const id = file.replace(".md", "");
          const pellet = await this.get(id);
          if (pellet) pellets.push(pellet);
        }
      }

      // Sort by most recently generated
      const sorted = pellets.sort((a, b) => {
        return (
          new Date(b.generatedAt).getTime() - new Date(a.generatedAt).getTime()
        );
      });

      // Cache the result
      this.listAllCache = sorted;
      this.cacheExpiresAt = Date.now() + PelletStore.CACHE_TTL_MS;

      return sorted;
    } catch (error) {
      console.error("[PelletStore] Failed to list pellets:", error);
      return [];
    }
  }

  /**
   * Delete a pellet by ID and remove it from the search index.
   */
  async delete(id: string): Promise<boolean> {
    const mdPath = join(this.pelletsDir, `${id}.md`);
    if (existsSync(mdPath)) {
      await unlink(mdPath);
      this.listAllCache = null; // Invalidate cache
      this.tfidf.removeDocument(id);
      await this.tfidf.persist();
      return true;
    }
    return false;
  }

  /**
   * Search pellets by query using BM25-ranked TF-IDF.
   *
   * Returns pellets sorted by relevance — title matches and tag matches
   * are boosted above content matches.  No embedding model required.
   */
  async search(query: string): Promise<Pellet[]> {
    const all = await this.listAll();
    if (all.length === 0 || !query.trim()) return all;

    const results = this.tfidf.search(query);
    if (results.length === 0) return [];

    const pelletMap = new Map(all.map((p) => [p.id, p]));
    return results
      .map((r) => pelletMap.get(r.id))
      .filter((p): p is Pellet => p !== undefined);
  }
}
