/**
 * StackOwl — Pellet Store (LanceDB + Kuzu backend)
 *
 * Manages the "Pellets" knowledge base — structured knowledge artifacts
 * generated by owls from conversations, research, and evolution cycles.
 *
 * Backend:
 *   - LanceDB: vector storage + cosine similarity search (replaces BM25/TF-IDF)
 *   - Kuzu:    persistent knowledge graph (replaces in-memory graphology)
 *
 * Public API is unchanged — all existing callers work without modification.
 *
 * Migration: on first init, scans workspace/pellets/*.md and imports them
 * into LanceDB + Kuzu automatically.
 */

import { join } from "node:path";
import { readFile, readdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import matter from "gray-matter";
import type { ModelProvider } from "../providers/base.js";
import { LancePelletStore } from "./lance-store.js";
import { KuzuPelletGraph } from "./kuzu-graph.js";
import { PelletDeduplicator, type DedupConfig, type DedupResult } from "./dedup.js";
import { embed, pelletToEmbedText } from "./embedder.js";
import { log } from "../logger.js";

export type { DedupResult, DedupConfig };

// ─── Pellet schema ───────────────────────────────────────────────

export interface Pellet {
  id: string;
  title: string;
  generatedAt: string;
  source: string;
  owls: string[];
  tags: string[];
  content: string;
  version: number;
  supersedes?: string;
  mergedFrom?: string[];
  lastMergedAt?: string;
}

// ─── PelletStore ─────────────────────────────────────────────────

export class PelletStore {
  private lance: LancePelletStore;
  private graph: KuzuPelletGraph;
  private deduplicator: PelletDeduplicator;

  /** Expose for CLI tools (graph build, stats) */
  get kuzuGraph(): KuzuPelletGraph {
    return this.graph;
  }

  constructor(
    private readonly workspacePath: string,
    provider?: ModelProvider,
    dedupConfig?: Partial<DedupConfig>,
  ) {
    this.lance = new LancePelletStore(workspacePath);
    this.graph = new KuzuPelletGraph(workspacePath);

    // Dedup uses LanceDB vector search instead of TF-IDF
    this.deduplicator = new PelletDeduplicator(
      async (pellet, limit) => {
        return this.lance.findSimilarTo(pellet, limit);
      },
      provider,
      dedupConfig,
    );
  }

  // ─── Init ──────────────────────────────────────────────────────

  private _initialized = false;
  private _initPromise: Promise<void> | null = null;

  /**
   * Initialize LanceDB + Kuzu.
   * Idempotent — safe to call multiple times or concurrently.
   * On first run: migrates existing markdown pellets (backward compat).
   */
  async init(): Promise<void> {
    if (this._initialized) return;
    // Serialize concurrent callers — only one init runs at a time
    if (this._initPromise) return this._initPromise;
    this._initPromise = this._doInit().finally(() => {
      this._initialized = true;
      this._initPromise = null;
    });
    return this._initPromise;
  }

  private async _doInit(): Promise<void> {
    await this.lance.init();
    await this.graph.init();

    // Migration: if LanceDB is empty but markdown files exist, import them
    const count = await this.lance.count();
    if (count === 0) {
      await this.migrateFromMarkdown();
    }
  }

  private async migrateFromMarkdown(): Promise<void> {
    const pelletsDir = join(this.workspacePath, "pellets");
    if (!existsSync(pelletsDir)) return;

    let files: string[];
    try {
      files = (await readdir(pelletsDir)).filter((f) => f.endsWith(".md"));
    } catch {
      return;
    }

    if (files.length === 0) return;

    log.engine.info(
      `[PelletStore] Migrating ${files.length} .md files to LanceDB+Kuzu...`,
    );

    const pellets: Pellet[] = [];
    for (const file of files) {
      const p = await this.readMarkdownPellet(join(pelletsDir, file));
      if (p) pellets.push(p);
    }

    await this.lance.migrate(pellets);

    // Build graph after migration
    await this.graph.buildFromPellets(pellets, async (p) => {
      const hits = await this.lance.findSimilarTo(p, 5, 0.45);
      return hits.map((h) => ({ id: h.pellet.id, score: h.score }));
    });

    log.engine.info(
      `[PelletStore] Migration complete. ` +
      `You may delete workspace/pellets/*.md files (they are no longer used).`,
    );
  }

  /** Parse a legacy markdown pellet file. */
  private async readMarkdownPellet(path: string): Promise<Pellet | null> {
    try {
      const raw = await readFile(path, "utf-8");
      const { data, content } = matter(raw);
      const id = path.split("/").pop()!.replace(".md", "");
      const p: Pellet = {
        id,
        title: data.title || id,
        generatedAt: data.generated_at || new Date().toISOString(),
        source: data.source || "unknown",
        owls: Array.isArray(data.owls) ? data.owls : [],
        tags: Array.isArray(data.tags) ? data.tags : [],
        version: data.version || 1,
        content: content.trim(),
      };
      if (data.supersedes) p.supersedes = data.supersedes;
      if (Array.isArray(data.merged_from)) p.mergedFrom = data.merged_from;
      if (data.last_merged_at) p.lastMergedAt = data.last_merged_at;
      return p;
    } catch {
      return null;
    }
  }

  // ─── Write ─────────────────────────────────────────────────────

  /**
   * Save a pellet with smart deduplication.
   *
   * Before writing, checks for semantically similar existing pellets.
   * The AI model decides whether to create, merge, supersede, or skip.
   */
  async save(
    pellet: Pellet,
    opts?: { skipDedup?: boolean },
  ): Promise<DedupResult> {
    await this.init();

    if (!opts?.skipDedup) {
      const decision = await this.deduplicator.evaluate(pellet);

      switch (decision.verdict) {
        case "SKIP":
          log.engine.info(
            `[PelletStore] SKIP: "${pellet.title.slice(0, 60)}" — ${decision.reasoning}`,
          );
          return decision;

        case "MERGE": {
          const existing = decision.targetPelletId
            ? await this.get(decision.targetPelletId)
            : null;
          if (existing) {
            existing.content = decision.mergedContent || existing.content;
            existing.title = decision.mergedTitle || existing.title;
            existing.tags = decision.mergedTags || [
              ...new Set([...existing.tags, ...pellet.tags]),
            ];
            existing.owls = [...new Set([...existing.owls, ...pellet.owls])];
            existing.version = (existing.version || 1) + 1;
            existing.mergedFrom = [...(existing.mergedFrom || []), pellet.id];
            existing.lastMergedAt = new Date().toISOString();
            await this.writePellet(existing);
            log.engine.info(
              `[PelletStore] MERGE: "${pellet.title.slice(0, 50)}" → "${existing.id}" (v${existing.version})`,
            );
            return decision;
          }
          break; // existing gone — fall through to create
        }

        case "SUPERSEDE": {
          pellet.supersedes = decision.targetPelletId;
          await this.writePellet(pellet);
          if (decision.targetPelletId) {
            await this.delete(decision.targetPelletId);
          }
          log.engine.info(
            `[PelletStore] SUPERSEDE: "${pellet.title.slice(0, 50)}" replaces "${decision.targetPelletId}"`,
          );
          return decision;
        }

        case "CREATE":
        default:
          break;
      }
    }

    await this.writePellet(pellet);
    return { verdict: "CREATE", reasoning: "new pellet" };
  }

  private async writePellet(pellet: Pellet): Promise<void> {
    const vec = await embed(pelletToEmbedText(pellet));
    await this.lance.upsert(pellet, vec ?? undefined);

    // Keep graph in sync
    if (this.graph.isBuilt) {
      await this.graph.addNode(pellet);
      // Add vector-similarity edges to existing pellets
      if (vec) {
        const similar = await this.lance.findSimilarTo(pellet, 5, 0.45);
        for (const { pellet: neighbor, score } of similar) {
          await this.graph
            .addEdge(pellet.id, neighbor.id, "vector_sim", score)
            .catch((e) => log.engine.warn(`[PelletStore] addEdge failed: ${e instanceof Error ? e.message : e}`));
        }
      }
    }
  }

  // ─── Read ──────────────────────────────────────────────────────

  /** Fetch a pellet by id. */
  async get(id: string): Promise<Pellet | null> {
    await this.init();
    return this.lance.get(id);
  }

  /** All pellets sorted by generatedAt desc. */
  async listAll(): Promise<Pellet[]> {
    await this.init();
    return this.lance.listAll();
  }

  async delete(id: string): Promise<void> {
    await this.init();
    await this.lance.delete(id);
    if (this.graph.isBuilt) {
      await this.graph.removeNode(id).catch((e) => log.engine.warn(`[PelletStore] removeNode failed: ${e instanceof Error ? e.message : e}`));
    }
  }

  // ─── Search ────────────────────────────────────────────────────

  /**
   * Semantic similarity search using embeddings.
   * Replaces BM25/TF-IDF. `threshold` is cosine similarity (0–1).
   */
  async search(
    query: string,
    limit = 5,
    threshold = 0.4,
  ): Promise<Pellet[]> {
    await this.init();

    const vec = await embed(query);
    if (!vec) {
      // No embedder — fall back to title/tag scan
      return this.keywordFallback(query, limit);
    }

    const maxDist = 1 - threshold; // convert similarity threshold → distance threshold
    const hits = await this.lance.searchSimilar(vec, limit, maxDist);
    return hits.map((h) => h.pellet);
  }

  /**
   * GraphRAG search: vector seeds + Kuzu graph expansion.
   * Returns richer results than plain vector search for related concepts.
   */
  async searchWithGraph(query: string, limit = 10): Promise<Pellet[]> {
    await this.init();

    const vec = await embed(query);
    if (!vec) return this.keywordFallback(query, limit);

    // Step 1: vector seeds (top 5, cosine distance < 0.55)
    const seeds = await this.lance.searchSimilar(vec, 5, 0.55);
    if (seeds.length === 0) return [];

    // Step 2: expand seeds via Kuzu graph (1-hop neighbors)
    const neighborIds = new Set<string>(seeds.map((s) => s.pellet.id));
    if (this.graph.isBuilt) {
      for (const { pellet: seed } of seeds) {
        const neighbors = await this.graph
          .getNeighbors(seed.id, 1, 8)
          .catch(() => [] as string[]);
        neighbors.forEach((id) => neighborIds.add(id));
      }
    }

    // Step 3: fetch all candidates from LanceDB
    const candidates = await this.lance.getByIds([...neighborIds]);

    // Step 4: score candidates
    // Seeds get their vector similarity score; graph neighbors get a fixed 0.35 bonus
    const seedScores = new Map(seeds.map((s) => [s.pellet.id, s.score]));
    const scored = candidates.map((p) => ({
      pellet: p,
      score: seedScores.has(p.id)
        ? seedScores.get(p.id)! * 0.8 + 0.2
        : 0.35,
    }));

    return scored
      .sort((a, b) => b.score - a.score)
      .slice(0, limit)
      .map((s) => s.pellet);
  }

  // ─── Keyword fallback (no embedder) ────────────────────────────

  private async keywordFallback(query: string, limit: number): Promise<Pellet[]> {
    const all = await this.lance.listAll();
    const q = query.toLowerCase();
    const scored = all
      .map((p) => {
        let score = 0;
        if (p.title.toLowerCase().includes(q)) score += 3;
        if (p.tags.some((t) => t.toLowerCase().includes(q))) score += 2;
        if (p.content.toLowerCase().includes(q)) score += 1;
        return { p, score };
      })
      .filter(({ score }) => score > 0)
      .sort((a, b) => b.score - a.score);
    return scored.slice(0, limit).map(({ p }) => p);
  }

  // ─── Graph lifecycle ───────────────────────────────────────────

  /**
   * Rebuild the Kuzu graph from all LanceDB pellets.
   * Called on startup or via `stackowl graph build` CLI.
   */
  async buildGraph(): Promise<void> {
    await this.init();
    const pellets = await this.lance.listAll();

    await this.graph.buildFromPellets(pellets, async (p) => {
      const hits = await this.lance.findSimilarTo(p, 5, 0.45);
      return hits.map((h) => ({ id: h.pellet.id, score: h.score }));
    });
  }

  // ─── Backward compat shims ─────────────────────────────────────
  // These kept existing callers (bulk-dedup, CLI) working.

  /** @deprecated use kuzuGraph.getStats() directly */
  getDeduplicator(): PelletDeduplicator {
    return this.deduplicator;
  }

  /** @deprecated TF-IDF engine removed; returns dummy for compat */
  getTfIdf(): null {
    return null;
  }
}
