"""localize — stub i18n helper for setup strings (ARCH-94, multilingual requirement)."""

from __future__ import annotations

from stackowl.infra.observability import log

# Map of (key, lang) -> translated string.
# Production would load from locale files; this stub returns the key for any lang
# not explicitly listed here.
_STRINGS: dict[tuple[str, str], str] = {
    # EU AI Act disclosure
    ("ai_act_disclosure", "en"): (
        "This response is generated by an AI assistant (StackOwl). "
        "AI can make mistakes. Verify important information independently."
    ),
    ("ai_act_disclosure", "de"): (
        "Diese Antwort wurde von einem KI-Assistenten (StackOwl) generiert. "
        "KI kann Fehler machen. Überprüfen Sie wichtige Informationen unabhängig."
    ),
    ("ai_act_disclosure", "fr"): (
        "Cette réponse est générée par un assistant IA (StackOwl). "
        "L'IA peut faire des erreurs. Vérifiez les informations importantes indépendamment."
    ),
    ("ai_act_disclosure", "es"): (
        "Esta respuesta es generada por un asistente de IA (StackOwl). "
        "La IA puede cometer errores. Verifique la información importante de forma independiente."
    ),
    # Setup flow strings
    ("setup_ready", "en"): "✓ StackOwl is ready — run stackowl serve to start",
    ("setup_ready", "de"): "✓ StackOwl ist bereit — führen Sie stackowl serve aus",
    ("setup_ready", "fr"): "✓ StackOwl est prêt — exécutez stackowl serve pour démarrer",
    ("setup_demo_intro", "en"): (
        "StackOwl Demo Mode\n"
        "==================\n"
        "No API key required. Using MockProvider for all responses.\n"
        "Run: stackowl serve --provider mock"
    ),
    # Self-heal turn supervisor floor — 5 slots: {goal} {failed_capability} {attempts} {partial} {error}
    # Self-heal substitution note (W3.T14) — prepended to a substituted observation
    # so the model knows an ALTERNATIVE capability produced this result. 2 slots:
    # {failed} (the tool that failed) {sibling} (the in-bounds non-consequential
    # sibling that served the same capability class).
    ("self_heal_substituted", "en"): (
        "[note: '{failed}' was unavailable, so the equivalent capability "
        "'{sibling}' produced the following result instead.]"
    ),
    ("self_heal_substituted", "de"): (
        "[Hinweis: '{failed}' war nicht verfügbar, daher hat die gleichwertige "
        "Fähigkeit '{sibling}' stattdessen das folgende Ergebnis geliefert.]"
    ),
    # Applied-lesson explainability (pillar ④) — appended after a real answer when
    # the model self-reported via note_applied_lesson. 1 slot: {what_you_did}.
    ("self_heal_applied_lesson", "en"): "ℹ️ I drew on something I learned: {what_you_did}",
    ("self_heal_applied_lesson", "de"): "ℹ️ Ich habe Gelerntes genutzt: {what_you_did}",
    ("self_heal_applied_lesson", "fr"): "ℹ️ Je me suis appuyé sur un acquis : {what_you_did}",
    ("self_heal_applied_lesson", "es"): "ℹ️ Me apoyé en algo que aprendí: {what_you_did}",
    # Recovery explainability (pillar ④) — appended after a real answer when a
    # capability substitution recovered the turn. 2 slots: {failed} {recovered_via}.
    ("self_heal_recovery_note", "en"): "ℹ️ '{failed}' was unavailable, so I used '{recovered_via}' to complete this.",
    ("self_heal_recovery_note", "de"): "ℹ️ '{failed}' war nicht verfügbar, daher habe ich '{recovered_via}' verwendet.",
    ("self_heal_recovery_note", "fr"): "ℹ️ '{failed}' était indisponible, j'ai donc utilisé '{recovered_via}'.",
    ("self_heal_recovery_note", "es"): "ℹ️ '{failed}' no estaba disponible, así que usé '{recovered_via}'.",
    # Provider fallback recovery (pillar ④) — GENERIC, no provider/tier names leaked
    # to the user (names live in the [recovery] turn summary log only). No slots.
    ("self_heal_recovery_provider", "en"): (
        "ℹ️ The usual model was unavailable, so a backup completed this."
    ),
    ("self_heal_recovery_provider", "de"): (
        "ℹ️ Das übliche Modell war nicht verfügbar, daher hat ein Ersatzmodell dies erledigt."
    ),
    ("self_heal_recovery_provider", "fr"): (
        "ℹ️ Le modèle habituel était indisponible, un modèle de secours a donc traité cette demande."
    ),
    ("self_heal_recovery_provider", "es"): (
        "ℹ️ El modelo habitual no estaba disponible, así que un modelo de respaldo completó esto."
    ),
    # Recovery attempted before an honest give-up (pillar ④ / F-10) — GENERIC, no
    # names: surfaced ALONGSIDE the honest floor so the user knows alternatives were
    # tried before surrendering ("I tried alternatives before giving up"). No slots.
    ("self_heal_recovery_attempted", "en"): (
        "ℹ️ I tried alternative approaches before giving up."
    ),
    ("self_heal_recovery_attempted", "de"): (
        "ℹ️ Ich habe alternative Ansätze versucht, bevor ich aufgegeben habe."
    ),
    ("self_heal_recovery_attempted", "fr"): (
        "ℹ️ J'ai essayé d'autres approches avant d'abandonner."
    ),
    ("self_heal_recovery_attempted", "es"): (
        "ℹ️ Intenté enfoques alternativos antes de rendirme."
    ),
    # Static minimal fallback for the floor (used when template interpolation fails)
    ("self_heal_floor_minimal", "en"): (
        "I hit a problem completing this and couldn't finish; "
        "the technical detail is in the logs."
    ),
    ("self_heal_floor_minimal", "de"): (
        "Bei der Ausführung ist ein Problem aufgetreten und ich konnte nicht fertigstellen; "
        "das technische Detail befindet sich in den Protokollen."
    ),
    ("self_heal_floor_minimal", "fr"): (
        "J'ai rencontré un problème en réalisant ceci et je n'ai pas pu terminer ; "
        "le détail technique se trouve dans les journaux."
    ),
    ("self_heal_floor_minimal", "es"): (
        "Tuve un problema al completar esto y no pude terminar; "
        "el detalle técnico está en los registros."
    ),
    # Lean-window capability-honest floor suffix (appended to self_heal_floor when lean=True).
    # Appended with a space separator. No slots — must be safe as a static clause.
    # Informs the user that the current model's capacity was a factor in the failure.
    ("self_heal_floor_lean_suffix", "en"): (
        "Note: the current model has a limited context window, "
        "which may have contributed to this limitation."
    ),
    ("self_heal_floor_lean_suffix", "de"): (
        "Hinweis: Das aktuelle Modell verfügt über ein begrenztes Kontextfenster, "
        "was zu dieser Einschränkung beigetragen haben kann."
    ),
    ("self_heal_floor_lean_suffix", "fr"): (
        "Remarque : le modèle actuel dispose d'une fenêtre de contexte limitée, "
        "ce qui a pu contribuer à cette limitation."
    ),
    ("self_heal_floor_lean_suffix", "es"): (
        "Nota: el modelo actual tiene una ventana de contexto limitada, "
        "lo que puede haber contribuido a esta limitación."
    ),
    # Graceful floor for a give-up with NO real capability data (e.g. a bare
    # time/step backstop timeout): warm + honest, NO slots so nothing internal
    # (raw error, blank fields) can leak. Used by synthesize_floor's no-data branch.
    # Attempts exist but NO step reported a failure. Naming attempts[0] would
    # claim a capability failed when it may have succeeded, so the capability and
    # technical-detail sentences are omitted rather than rendered blank (live
    # 2026-08-15: "The capability that failed: . ... Technical detail: ").
    # ---------------------------------------------------------------- #
    # PER-SENTENCE floor keys. The floor used to pick one of three whole-message
    # templates, but the data has 2**3 = 8 shapes (capability? attempts? error?)
    # and only 3 had a template — so the other five fell through to the five-slot
    # one and rendered its missing sentences as bare punctuation. MEASURED
    # 2026-09-03: 81 of the 133 floors sent since the 2026-08-15 repairs still
    # carried a blank slot. Adding an eighth template is what produced that; these
    # keys let the message be COMPOSED from the sentences that have data, so there
    # is no combination left to miss.
    #
    # Each ends with its own trailing space so they concatenate directly. The
    # goal sentence is taken from ``self_heal_floor`` rather than
    # ``self_heal_floor_unattributed`` — the two had already drifted in French
    # ("terminer ceci" vs "terminer complètement ceci"), which is what two copies
    # of one sentence always does.
    ("self_heal_floor_s_goal", "en"): "I couldn't fully complete this: {goal}. ",
    ("self_heal_floor_s_goal", "de"): "Ich konnte dies nicht vollständig erledigen: {goal}. ",
    ("self_heal_floor_s_goal", "fr"): "Je n'ai pas pu terminer complètement ceci : {goal}. ",
    ("self_heal_floor_s_goal", "es"): "No pude completar esto del todo: {goal}. ",
    # The lead sentence when the goal did not survive. delivery_gate passes
    # strip_turn_context(state.input_text), which CAN strip to "" — and the
    # goal-bearing sentence would then render "I couldn't fully complete this: ."
    ("self_heal_floor_s_nogoal", "en"): "I couldn't fully complete that. ",
    ("self_heal_floor_s_nogoal", "de"): "Ich konnte das nicht vollständig erledigen. ",
    ("self_heal_floor_s_nogoal", "fr"): "Je n'ai pas pu terminer complètement cela. ",
    ("self_heal_floor_s_nogoal", "es"): "No pude completar eso del todo. ",
    ("self_heal_floor_s_capability", "en"): "The capability that failed: {failed_capability}. ",
    ("self_heal_floor_s_capability", "de"): "Die fehlgeschlagene Fähigkeit: {failed_capability}. ",
    ("self_heal_floor_s_capability", "fr"): "La capacité qui a échoué : {failed_capability}. ",
    ("self_heal_floor_s_capability", "es"): "La capacidad que falló: {failed_capability}. ",
    ("self_heal_floor_s_attempts", "en"): "What I tried: {attempts}. ",
    ("self_heal_floor_s_attempts", "de"): "Was ich versucht habe: {attempts}. ",
    ("self_heal_floor_s_attempts", "fr"): "Ce que j'ai essayé : {attempts}. ",
    ("self_heal_floor_s_attempts", "es"): "Lo que intenté: {attempts}. ",
    ("self_heal_floor_s_error", "en"): "Technical detail: {error}",
    ("self_heal_floor_s_error", "de"): "Technisches Detail: {error}",
    ("self_heal_floor_s_error", "fr"): "Détail technique : {error}",
    ("self_heal_floor_s_error", "es"): "Detalle técnico : {error}",
    # The closer for a turn that tried things but could attribute no failure.
    # Naming attempts[0] would accuse a capability that may have SUCCEEDED.
    ("self_heal_floor_s_no_attribution", "en"): (
        "No single step reported a failure, so I can't say which one went wrong."
    ),
    ("self_heal_floor_s_no_attribution", "de"): (
        "Kein einzelner Schritt meldete einen Fehler, daher kann ich nicht sagen, "
        "welcher schiefging."
    ),
    ("self_heal_floor_s_no_attribution", "fr"): (
        "Aucune étape n'a signalé d'échec, je ne peux donc pas dire laquelle a "
        "posé problème."
    ),
    ("self_heal_floor_s_no_attribution", "es"): (
        "Ningún paso informó de un fallo, así que no puedo decir cuál salió mal."
    ),
    # ---------------------------------------------------------------- #
    # PLAIN-LANGUAGE CAUSES for the failures he actually receives.
    #
    # MEASURED 2026-09-03 over every failed turn on his Telegram channel: 3,856
    # of 5,739 (67%) told him "the technical detail is in the logs" — logs he
    # cannot reach from Telegram — with a Python exception class in brackets.
    # These four classes are 5,384 of those failures (94%):
    # AllProvidersUnavailableError 2,115, OwlTimeoutError 1,800,
    # CircuitOpenError 1,258, ProviderError 211. Each is an infrastructure
    # condition with a one-sentence explanation the platform already knew.
    #
    # DERIVED FROM THE DATA, not from a guess about what might go wrong: the
    # list is exactly the classes measured as reaching him. A class that is not
    # here gets the generic prose, because inventing a cause for an unknown
    # failure is the overclaim the honest floor exists to prevent.
    ("floor_cause_AllProvidersUnavailableError", "en"): (
        "I could not reach my model just now, so I could not work on this. "
        "It usually comes back on its own — ask me again in a moment."
    ),
    ("floor_cause_AllProvidersUnavailableError", "de"): (
        "Ich konnte mein Modell gerade nicht erreichen und daher nicht daran "
        "arbeiten. Das behebt sich meist von selbst — frag mich gleich noch einmal."
    ),
    ("floor_cause_AllProvidersUnavailableError", "fr"): (
        "Je n'ai pas pu joindre mon modèle à l'instant, donc je n'ai pas pu "
        "traiter cela. Cela se rétablit généralement seul — redemande-moi dans un moment."
    ),
    ("floor_cause_AllProvidersUnavailableError", "es"): (
        "No pude conectar con mi modelo en este momento, así que no pude "
        "trabajar en esto. Suele restablecerse solo — pregúntame de nuevo en un momento."
    ),
    ("floor_cause_OwlTimeoutError", "en"): (
        "This took longer than I am allowed to spend on one turn, so I stopped "
        "rather than leave you waiting."
    ),
    ("floor_cause_OwlTimeoutError", "de"): (
        "Das hat länger gedauert, als ich für einen Zug aufwenden darf, also habe "
        "ich abgebrochen, statt dich warten zu lassen."
    ),
    ("floor_cause_OwlTimeoutError", "fr"): (
        "Cela a pris plus de temps que ce que je peux consacrer à un tour, donc "
        "je me suis arrêté plutôt que de te faire attendre."
    ),
    ("floor_cause_OwlTimeoutError", "es"): (
        "Esto tardó más de lo que puedo dedicar a un turno, así que me detuve en "
        "lugar de dejarte esperando."
    ),
    ("floor_cause_CircuitOpenError", "en"): (
        "I have paused calls to my model after several failures in a row, so this "
        "one was not attempted. It retries automatically."
    ),
    ("floor_cause_CircuitOpenError", "de"): (
        "Ich habe die Aufrufe an mein Modell nach mehreren Fehlern in Folge "
        "pausiert, daher wurde dies nicht versucht. Es wird automatisch erneut versucht."
    ),
    ("floor_cause_CircuitOpenError", "fr"): (
        "J'ai suspendu les appels à mon modèle après plusieurs échecs consécutifs, "
        "donc celui-ci n'a pas été tenté. Il réessaiera automatiquement."
    ),
    ("floor_cause_CircuitOpenError", "es"): (
        "He pausado las llamadas a mi modelo tras varios fallos seguidos, así que "
        "esto no se intentó. Se reintenta automáticamente."
    ),
    ("floor_cause_ProviderError", "en"): (
        "My model returned an error on this one, so I could not finish it."
    ),
    ("floor_cause_ProviderError", "de"): (
        "Mein Modell hat hierbei einen Fehler zurückgegeben, daher konnte ich es "
        "nicht abschließen."
    ),
    ("floor_cause_ProviderError", "fr"): (
        "Mon modèle a renvoyé une erreur sur celui-ci, je n'ai donc pas pu le terminer."
    ),
    ("floor_cause_ProviderError", "es"): (
        "Mi modelo devolvió un error en este caso, así que no pude terminarlo."
    ),
    ("self_heal_floor_graceful", "en"): (
        "Sorry — I got tangled up working on that and didn't finish cleanly. "
        "Could you tell me a bit more, or say it another way?"
    ),
    ("self_heal_floor_graceful", "de"): (
        "Entschuldigung — ich habe mich dabei verheddert und es nicht sauber "
        "abgeschlossen. Kannst du es anders formulieren oder mehr dazu sagen?"
    ),
    ("self_heal_floor_graceful", "fr"): (
        "Désolé — je me suis emmêlé et je n'ai pas terminé proprement. "
        "Peux-tu reformuler ou m'en dire un peu plus ?"
    ),
    ("self_heal_floor_graceful", "es"): (
        "Perdona — me hice un lío con eso y no terminé bien. "
        "¿Puedes decirlo de otra forma o darme algún detalle más?"
    ),
}


def localize(key: str, lang: str = "en") -> str:
    """Return the localised string for *key* in *lang*, falling back to English then the key itself."""
    result = _STRINGS.get((key, lang))
    if result is not None:
        return result
    en_result = _STRINGS.get((key, "en"))
    if en_result is not None:
        return en_result
    return key


class _SafeDict(dict):  # type: ignore[type-arg]
    """dict subclass whose __missing__ returns an empty string for unknown slots."""

    def __missing__(self, key: str) -> str:  # noqa: D105
        return ""


def localize_format(key: str, lang: str = "en", **slots: object) -> str:
    """Return the localised template for *key*/*lang* with *slots* interpolated.

    Safe: missing slots produce an empty string (never a KeyError). Any
    unexpected error falls back to the raw template string.  Never raises,
    never returns empty.
    """
    log.setup.debug(
        "localize_format: entry",
        extra={"_fields": {"key": key, "lang": lang, "slot_keys": list(slots)}},
    )
    template = localize(key, lang)
    try:
        result = template.format_map(_SafeDict({k: str(v) for k, v in slots.items()}))
        log.setup.debug(
            "localize_format: exit",
            extra={"_fields": {"key": key, "result_len": len(result)}},
        )
        return result
    except Exception as exc:  # noqa: BLE001
        log.setup.error(
            "localize_format: interpolation failed",
            exc_info=exc,
            extra={"_fields": {"key": key, "lang": lang}},
        )
        return template
