-- Migration 0030 reflections
-- One row per "lesson learned" generated by the ReflectionWriterHandler after
-- the critic scores a low-quality or failed outcome. Reflexion-style — the
-- summary + suggested_strategy become retrievable artifacts that classify.py
-- surfaces in future runs facing similar failure_class or query semantics.
-- Telemetry/learning artifact, NOT a fact — kept separate from staged_facts
-- so it never gets promoted to committed knowledge (operator-approved
-- Commit 2 vote, plan gleaming-finding-puppy.md).
-- NOTE no semicolons in comments per migration runner gotcha.

CREATE TABLE IF NOT EXISTS reflections (
    reflection_id      INTEGER PRIMARY KEY AUTOINCREMENT,
    trace_id           TEXT    NOT NULL,
    owl_name           TEXT    NOT NULL,
    summary            TEXT    NOT NULL,
    suggested_strategy TEXT    NOT NULL DEFAULT '',
    failure_class      TEXT,
    quality_score      REAL,
    embedding          BLOB,
    embedding_model    TEXT,
    created_at         REAL    NOT NULL,
    UNIQUE(trace_id)
);

CREATE INDEX IF NOT EXISTS idx_reflections_owl ON reflections(owl_name);
CREATE INDEX IF NOT EXISTS idx_reflections_failure ON reflections(failure_class);
CREATE INDEX IF NOT EXISTS idx_reflections_created ON reflections(created_at);
