"""localize — stub i18n helper for setup strings (ARCH-94, multilingual requirement)."""

from __future__ import annotations

from stackowl.infra.observability import log

# Map of (key, lang) -> translated string.
# Production would load from locale files; this stub returns the key for any lang
# not explicitly listed here.
_STRINGS: dict[tuple[str, str], str] = {
    # EU AI Act disclosure
    ("ai_act_disclosure", "en"): (
        "This response is generated by an AI assistant (StackOwl). "
        "AI can make mistakes. Verify important information independently."
    ),
    ("ai_act_disclosure", "de"): (
        "Diese Antwort wurde von einem KI-Assistenten (StackOwl) generiert. "
        "KI kann Fehler machen. Überprüfen Sie wichtige Informationen unabhängig."
    ),
    ("ai_act_disclosure", "fr"): (
        "Cette réponse est générée par un assistant IA (StackOwl). "
        "L'IA peut faire des erreurs. Vérifiez les informations importantes indépendamment."
    ),
    ("ai_act_disclosure", "es"): (
        "Esta respuesta es generada por un asistente de IA (StackOwl). "
        "La IA puede cometer errores. Verifique la información importante de forma independiente."
    ),
    # Setup flow strings
    ("setup_ready", "en"): "✓ StackOwl is ready — run stackowl serve to start",
    ("setup_ready", "de"): "✓ StackOwl ist bereit — führen Sie stackowl serve aus",
    ("setup_ready", "fr"): "✓ StackOwl est prêt — exécutez stackowl serve pour démarrer",
    ("setup_demo_intro", "en"): (
        "StackOwl Demo Mode\n"
        "==================\n"
        "No API key required. Using MockProvider for all responses.\n"
        "Run: stackowl serve --provider mock"
    ),
    # Self-heal turn supervisor floor — 5 slots: {goal} {failed_capability} {attempts} {partial} {error}
    ("self_heal_floor", "en"): (
        "I couldn't fully complete this: {goal}. "
        "The capability that failed: {failed_capability}. "
        "What I tried: {attempts}. "
        "{partial}"
        "Technical detail: {error}"
    ),
    ("self_heal_floor", "de"): (
        "Ich konnte dies nicht vollständig erledigen: {goal}. "
        "Die fehlgeschlagene Fähigkeit: {failed_capability}. "
        "Was ich versucht habe: {attempts}. "
        "{partial}"
        "Technisches Detail: {error}"
    ),
    # Static minimal fallback for the floor (used when template interpolation fails)
    ("self_heal_floor_minimal", "en"): (
        "I hit a problem completing this and couldn't finish; "
        "the technical detail is in the logs."
    ),
    ("self_heal_floor_minimal", "de"): (
        "Bei der Ausführung ist ein Problem aufgetreten und ich konnte nicht fertigstellen; "
        "das technische Detail befindet sich in den Protokollen."
    ),
}


def localize(key: str, lang: str = "en") -> str:
    """Return the localised string for *key* in *lang*, falling back to English then the key itself."""
    result = _STRINGS.get((key, lang))
    if result is not None:
        return result
    en_result = _STRINGS.get((key, "en"))
    if en_result is not None:
        return en_result
    return key


class _SafeDict(dict):  # type: ignore[type-arg]
    """dict subclass whose __missing__ returns an empty string for unknown slots."""

    def __missing__(self, key: str) -> str:  # noqa: D105
        return ""


def localize_format(key: str, lang: str = "en", **slots: object) -> str:
    """Return the localised template for *key*/*lang* with *slots* interpolated.

    Safe: missing slots produce an empty string (never a KeyError). Any
    unexpected error falls back to the raw template string.  Never raises,
    never returns empty.
    """
    log.gateway.debug("localize_format: entry", {"key": key, "lang": lang, "slot_keys": list(slots)})
    template = localize(key, lang)
    try:
        result = template.format_map(_SafeDict({k: str(v) for k, v in slots.items()}))
        log.gateway.debug("localize_format: exit", {"key": key, "result_len": len(result)})
        return result
    except Exception as exc:  # noqa: BLE001
        log.gateway.error("localize_format: interpolation failed", exc, {"key": key, "lang": lang})
        return template
