"""localize — stub i18n helper for setup strings (ARCH-94, multilingual requirement)."""

from __future__ import annotations

from stackowl.infra.observability import log

# Map of (key, lang) -> translated string.
# Production would load from locale files; this stub returns the key for any lang
# not explicitly listed here.
_STRINGS: dict[tuple[str, str], str] = {
    # EU AI Act disclosure
    ("ai_act_disclosure", "en"): (
        "This response is generated by an AI assistant (StackOwl). "
        "AI can make mistakes. Verify important information independently."
    ),
    ("ai_act_disclosure", "de"): (
        "Diese Antwort wurde von einem KI-Assistenten (StackOwl) generiert. "
        "KI kann Fehler machen. Überprüfen Sie wichtige Informationen unabhängig."
    ),
    ("ai_act_disclosure", "fr"): (
        "Cette réponse est générée par un assistant IA (StackOwl). "
        "L'IA peut faire des erreurs. Vérifiez les informations importantes indépendamment."
    ),
    ("ai_act_disclosure", "es"): (
        "Esta respuesta es generada por un asistente de IA (StackOwl). "
        "La IA puede cometer errores. Verifique la información importante de forma independiente."
    ),
    # Setup flow strings
    ("setup_ready", "en"): "✓ StackOwl is ready — run stackowl serve to start",
    ("setup_ready", "de"): "✓ StackOwl ist bereit — führen Sie stackowl serve aus",
    ("setup_ready", "fr"): "✓ StackOwl est prêt — exécutez stackowl serve pour démarrer",
    ("setup_demo_intro", "en"): (
        "StackOwl Demo Mode\n"
        "==================\n"
        "No API key required. Using MockProvider for all responses.\n"
        "Run: stackowl serve --provider mock"
    ),
    # Self-heal turn supervisor floor — 5 slots: {goal} {failed_capability} {attempts} {partial} {error}
    ("self_heal_floor", "en"): (
        "I couldn't fully complete this: {goal}. "
        "The capability that failed: {failed_capability}. "
        "What I tried: {attempts}. "
        "{partial} "
        "Technical detail: {error}"
    ),
    ("self_heal_floor", "de"): (
        "Ich konnte dies nicht vollständig erledigen: {goal}. "
        "Die fehlgeschlagene Fähigkeit: {failed_capability}. "
        "Was ich versucht habe: {attempts}. "
        "{partial} "
        "Technisches Detail: {error}"
    ),
    # Self-heal substitution note (W3.T14) — prepended to a substituted observation
    # so the model knows an ALTERNATIVE capability produced this result. 2 slots:
    # {failed} (the tool that failed) {sibling} (the in-bounds non-consequential
    # sibling that served the same capability class).
    ("self_heal_substituted", "en"): (
        "[note: '{failed}' was unavailable, so the equivalent capability "
        "'{sibling}' produced the following result instead.]"
    ),
    ("self_heal_substituted", "de"): (
        "[Hinweis: '{failed}' war nicht verfügbar, daher hat die gleichwertige "
        "Fähigkeit '{sibling}' stattdessen das folgende Ergebnis geliefert.]"
    ),
    # Applied-lesson explainability (pillar ④) — appended after a real answer when
    # the model self-reported via note_applied_lesson. 1 slot: {what_you_did}.
    ("self_heal_applied_lesson", "en"): "ℹ️ I drew on something I learned: {what_you_did}",
    ("self_heal_applied_lesson", "de"): "ℹ️ Ich habe Gelerntes genutzt: {what_you_did}",
    ("self_heal_applied_lesson", "fr"): "ℹ️ Je me suis appuyé sur un acquis : {what_you_did}",
    ("self_heal_applied_lesson", "es"): "ℹ️ Me apoyé en algo que aprendí: {what_you_did}",
    # Recovery explainability (pillar ④) — appended after a real answer when a
    # capability substitution recovered the turn. 2 slots: {failed} {recovered_via}.
    ("self_heal_recovery_note", "en"): "ℹ️ '{failed}' was unavailable, so I used '{recovered_via}' to complete this.",
    ("self_heal_recovery_note", "de"): "ℹ️ '{failed}' war nicht verfügbar, daher habe ich '{recovered_via}' verwendet.",
    ("self_heal_recovery_note", "fr"): "ℹ️ '{failed}' était indisponible, j'ai donc utilisé '{recovered_via}'.",
    ("self_heal_recovery_note", "es"): "ℹ️ '{failed}' no estaba disponible, así que usé '{recovered_via}'.",
    # Provider fallback recovery (pillar ④) — GENERIC, no provider/tier names leaked
    # to the user (names live in the [recovery] turn summary log only). No slots.
    ("self_heal_recovery_provider", "en"): (
        "ℹ️ The usual model was unavailable, so a backup completed this."
    ),
    ("self_heal_recovery_provider", "de"): (
        "ℹ️ Das übliche Modell war nicht verfügbar, daher hat ein Ersatzmodell dies erledigt."
    ),
    ("self_heal_recovery_provider", "fr"): (
        "ℹ️ Le modèle habituel était indisponible, un modèle de secours a donc traité cette demande."
    ),
    ("self_heal_recovery_provider", "es"): (
        "ℹ️ El modelo habitual no estaba disponible, así que un modelo de respaldo completó esto."
    ),
    # Static minimal fallback for the floor (used when template interpolation fails)
    ("self_heal_floor_minimal", "en"): (
        "I hit a problem completing this and couldn't finish; "
        "the technical detail is in the logs."
    ),
    ("self_heal_floor_minimal", "de"): (
        "Bei der Ausführung ist ein Problem aufgetreten und ich konnte nicht fertigstellen; "
        "das technische Detail befindet sich in den Protokollen."
    ),
    # Graceful floor for a give-up with NO real capability data (e.g. a bare
    # time/step backstop timeout): warm + honest, NO slots so nothing internal
    # (raw error, blank fields) can leak. Used by synthesize_floor's no-data branch.
    ("self_heal_floor_graceful", "en"): (
        "Sorry — I got tangled up working on that and didn't finish cleanly. "
        "Could you tell me a bit more, or say it another way?"
    ),
    ("self_heal_floor_graceful", "de"): (
        "Entschuldigung — ich habe mich dabei verheddert und es nicht sauber "
        "abgeschlossen. Kannst du es anders formulieren oder mehr dazu sagen?"
    ),
    ("self_heal_floor_graceful", "fr"): (
        "Désolé — je me suis emmêlé et je n'ai pas terminé proprement. "
        "Peux-tu reformuler ou m'en dire un peu plus ?"
    ),
    ("self_heal_floor_graceful", "es"): (
        "Perdona — me hice un lío con eso y no terminé bien. "
        "¿Puedes decirlo de otra forma o darme algún detalle más?"
    ),
}


def localize(key: str, lang: str = "en") -> str:
    """Return the localised string for *key* in *lang*, falling back to English then the key itself."""
    result = _STRINGS.get((key, lang))
    if result is not None:
        return result
    en_result = _STRINGS.get((key, "en"))
    if en_result is not None:
        return en_result
    return key


class _SafeDict(dict):  # type: ignore[type-arg]
    """dict subclass whose __missing__ returns an empty string for unknown slots."""

    def __missing__(self, key: str) -> str:  # noqa: D105
        return ""


def localize_format(key: str, lang: str = "en", **slots: object) -> str:
    """Return the localised template for *key*/*lang* with *slots* interpolated.

    Safe: missing slots produce an empty string (never a KeyError). Any
    unexpected error falls back to the raw template string.  Never raises,
    never returns empty.
    """
    log.setup.debug(
        "localize_format: entry",
        extra={"_fields": {"key": key, "lang": lang, "slot_keys": list(slots)}},
    )
    template = localize(key, lang)
    try:
        result = template.format_map(_SafeDict({k: str(v) for k, v in slots.items()}))
        log.setup.debug(
            "localize_format: exit",
            extra={"_fields": {"key": key, "result_len": len(result)}},
        )
        return result
    except Exception as exc:  # noqa: BLE001
        log.setup.error(
            "localize_format: interpolation failed",
            exc_info=exc,
            extra={"_fields": {"key": key, "lang": lang}},
        )
        return template
