#!/usr/bin/env python
"""Generate the annotated example config from the Settings model itself.

D18.2 adopts the reference platform's annotated example file as a docs artifact —
and deliberately not the way they maintain it. Theirs is 1,616 hand-written
lines, which is a second copy of the configuration surface: it can only be
correct until someone forgets to update it.

Ours is GENERATED from ``Settings``. Measured 2026-09-05 the surface is 210
settable fields across 33 top-level sections, and an operator's only alternative is
reading 1,100 lines of ``settings.py``. Hand-writing 210 entries would be stale
inside a week; deriving them cannot drift, and
``tests/test_the_example_config_cannot_go_stale.py`` fails the gate if the
checked-in file stops matching this script's output.

Descriptions come from each field's ``Field(description=...)``. Half the surface
carries one (107 of 210 when this shipped); a field without a description emits
no comment rather than an invented one, so the file shows honestly where the
documentation stops.

    uv run python scripts/gen_config_example.py            # print
    uv run python scripts/gen_config_example.py --write    # update the artifact
"""

from __future__ import annotations

import sys
from enum import Enum
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel

from stackowl.config.settings import Settings

_ARTIFACT = Path(__file__).resolve().parents[1] / "docs" / "stackowl.yaml.example"

_HEADER = """\
# StackOwl — annotated example configuration
#
# GENERATED by scripts/gen_config_example.py from the Settings model. Do not edit
# by hand: a test regenerates this file and fails if it differs, which is what
# keeps it from becoming a second, stale copy of the configuration surface.
#
# Every value shown is the DEFAULT. Delete what you do not want to change —
# an absent key uses the default, and this whole file is optional.
#
# Comments are each field's own description. Where a field has none, none is
# invented, so the gaps here are the gaps in the model's documentation.
#
# Secrets do NOT belong in this file. Store a REFERENCE instead:
#   some_api_key: "keychain:stackowl-anthropic"   # OS keychain (preferred)
#   some_api_key: "file:/run/secrets/anthropic"   # a file, whitespace stripped
#   some_api_key: "ANTHROPIC_API_KEY"             # an environment variable name
# See src/stackowl/config/secret_resolver.py.
#
# Environment variables are for bootstrap, host-specific and terminal-convention
# settings only — see tests/test_a_new_env_var_has_to_justify_itself.py for the
# taxonomy. Everything behavioural belongs here.
"""


def _symbolic_home(path: Path) -> str:
    """Render a StackOwl-home-derived path as ``~/.stackowl/...``.

    Three problems, one fix. These defaults RESOLVE against ``STACKOWL_HOME``, so
    the generated file otherwise carried an absolute machine path — which (1) is
    wrong on every other machine, (2) leaks the operator's home directory name
    into a docs artifact, and (3) makes the output environment-dependent, so the
    byte-comparison guard failed under pytest, where the home is a tmpdir. That
    failure is how all three were found.
    """
    from stackowl.paths import StackowlHome

    try:
        home = str(StackowlHome.home())
    except Exception:  # pragma: no cover - home should always resolve
        return str(path)
    text = str(path)
    return "~/.stackowl" + text[len(home):] if text.startswith(home) else text


def _plain(value: Any) -> Any:
    """Reduce a default to something ``yaml.safe_dump`` can represent.

    Pydantic defaults are richer than YAML: frozensets, tuples, Paths and Enums
    all appear here. A frozenset() default is what made the first run of this
    script raise RepresenterError, which is the argument for generating the file
    rather than trusting a hand-written one to have got every type right.
    Sets are SORTED so the output is byte-stable across runs — the guard
    compares bytes.
    """
    if isinstance(value, (frozenset, set)):
        return sorted(_plain(v) for v in value)
    if isinstance(value, tuple):
        return [_plain(v) for v in value]
    if isinstance(value, list):
        return [_plain(v) for v in value]
    if isinstance(value, dict):
        return {str(k): _plain(v) for k, v in value.items()}
    if isinstance(value, Path):
        return _symbolic_home(value)
    if isinstance(value, Enum):
        return _plain(value.value)
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    return str(value)


def _scalar(value: Any) -> str:
    """Render one default as a YAML scalar, deterministically."""
    dumped = yaml.safe_dump(_plain(value), default_flow_style=True, sort_keys=True).strip()
    return dumped.removesuffix("\n...").strip()


def _emit(model: type[BaseModel], indent: int, out: list[str]) -> None:
    pad = " " * indent
    for name, field in model.model_fields.items():
        annotation = field.annotation
        if isinstance(annotation, type) and issubclass(annotation, BaseModel):
            if field.description:
                out.append(f"{pad}# {field.description}")
            out.append(f"{pad}{name}:")
            _emit(annotation, indent + 2, out)
            out.append("")
            continue
        if field.description:
            for line in str(field.description).splitlines():
                out.append(f"{pad}# {line.strip()}")
        try:
            default = field.get_default(call_default_factory=True)
        except Exception:  # pragma: no cover - a default that cannot be built
            out.append(f"{pad}# {name}: <no representable default>")
            continue
        out.append(f"{pad}{name}: {_scalar(default)}")


def render() -> str:
    lines: list[str] = []
    _emit(Settings, 0, lines)
    body = "\n".join(lines).rstrip() + "\n"
    return _HEADER + "\n" + body


def main() -> int:
    text = render()
    if "--write" in sys.argv:
        _ARTIFACT.parent.mkdir(parents=True, exist_ok=True)
        _ARTIFACT.write_text(text, encoding="utf-8")
        print(f"wrote {_ARTIFACT} ({len(text.splitlines())} lines)")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
