#!/usr/bin/env python3
"""Generate `.claude/agents/*.md` subagent definitions from BMAD agent skills.

BMAD ships each agent (Winston, Mary, Murat, Dr. Quinn, …) as a *skill* under
`.claude/skills/bmad-*agent*` with a rich persona block in `customize.toml`. The
Claude Code Agent tool, however, only spawns subagents that are registered as
`.claude/agents/<name>.md` definition files. With no such files, party-mode and
any `Agent(subagent_type="bmad-...")` call fail with "agent type not found".

This script bridges that gap: it reads every BMAD agent skill's `customize.toml`
(persona: name/title/icon/role/identity/communication_style/principles/menu) plus
its `SKILL.md` frontmatter `description`, and emits a faithful, self-contained
subagent system prompt to `.claude/agents/<code>.md`. The subagent body is the
persona WITHOUT the interactive greet/menu activation ritual (a subagent performs
one task and returns), so the same persona works for party-mode roundtables and
for direct delegated work.

Idempotent + re-runnable: safe to run after any BMAD update. Files carry a
"GENERATED" banner so they are recognizable as machine-authored.

Usage (from repo root):
    python3 scripts/generate_bmad_subagents.py            # write
    python3 scripts/generate_bmad_subagents.py --check    # report, write nothing
"""
from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = REPO_ROOT / ".claude" / "skills"
AGENTS_DIR = REPO_ROOT / ".claude" / "agents"

BANNER = "<!-- GENERATED by scripts/generate_bmad_subagents.py — do not edit by hand; re-run to refresh. -->"


def _read_skill_description(skill_dir: Path) -> str:
    """Pull the `description:` line from the skill's SKILL.md YAML frontmatter."""
    skill_md = skill_dir / "SKILL.md"
    if not skill_md.is_file():
        return ""
    in_fm = False
    for line in skill_md.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped == "---":
            if not in_fm:
                in_fm = True
                continue
            break  # end of frontmatter
        if in_fm and stripped.lower().startswith("description:"):
            return stripped.split(":", 1)[1].strip()
    return ""


def _discover_agents() -> list[tuple[str, Path, dict]]:
    """Return (code, skill_dir, agent_block) for every BMAD agent skill."""
    found: list[tuple[str, Path, dict]] = []
    if not SKILLS_DIR.is_dir():
        return found
    for skill_dir in sorted(SKILLS_DIR.glob("bmad*")):
        toml_path = skill_dir / "customize.toml"
        if not toml_path.is_file():
            continue
        try:
            data = tomllib.loads(toml_path.read_text(encoding="utf-8"))
        except tomllib.TOMLDecodeError as exc:  # pragma: no cover - defensive
            print(f"  ! skip {skill_dir.name}: bad customize.toml ({exc})", file=sys.stderr)
            continue
        agent = data.get("agent")
        # An agent persona has a name + title; workflow skills (teach-me-testing)
        # may carry a [agent]-less customize.toml — filter those out.
        if not isinstance(agent, dict) or not agent.get("name") or not agent.get("title"):
            continue
        found.append((skill_dir.name, skill_dir, agent))
    return found


def _render(code: str, skill_dir: Path, agent: dict) -> str:
    name = str(agent.get("name", "")).strip()
    title = str(agent.get("title", "")).strip()
    icon = str(agent.get("icon", "")).strip()
    role = str(agent.get("role", "")).strip()
    identity = str(agent.get("identity", "")).strip()
    style = str(agent.get("communication_style", "")).strip()
    principles = [str(p).strip() for p in agent.get("principles", []) if str(p).strip()]
    menu = agent.get("menu", []) if isinstance(agent.get("menu"), list) else []

    description = _read_skill_description(skill_dir) or (
        f"{title}. Use when the user asks to talk to {name} or requests the {title.lower()}."
    )

    principle_lines = "\n".join(f"- {p}" for p in principles) or "- (none specified)"

    menu_lines = ""
    for item in menu:
        if not isinstance(item, dict):
            continue
        mcode = str(item.get("code", "")).strip()
        mdesc = str(item.get("description", "")).strip()
        skill = str(item.get("skill", "")).strip()
        target = f"`{skill}`" if skill else "(inline prompt)"
        if mcode or mdesc:
            menu_lines += f"- **{mcode}** — {mdesc} → {target}\n"
    menu_block = (
        f"\n## Capabilities (BMAD skills you can invoke)\n\n{menu_lines}" if menu_lines else ""
    )

    return f"""---
name: {code}
description: {description}
---
{BANNER}

# {icon} {name} — {title}

You are **{name}**, {title}. You are running as a subagent — you may be asked for
your independent perspective in a roundtable (party mode) or handed a concrete task
to execute. Either way, embody {name} fully and do not break character.

## Identity
{identity or "(see role)"}

## Role
{role or "(see identity)"}

## Communication Style
{style or "(natural to the persona)"}

## Principles
{principle_lines}
{menu_block}
## Operating notes
- Begin every response with {icon} **{name}:** so the active persona is identifiable.
- Speak with your authentic voice and ethos above. Disagree when your judgment says to — do not hedge to be polite.
- Scale your response to the substance; never pad. If you have nothing to add, say so in one sentence.
- In a roundtable, give a perspective and do NOT use tools unless the orchestrator explicitly asks. On a delegated task, use whatever tools the task requires.
- Your final message is the deliverable returned to the orchestrator — make it self-contained.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report only; write nothing")
    args = parser.parse_args()

    agents = _discover_agents()
    if not agents:
        print("No BMAD agent skills found under .claude/skills/bmad*", file=sys.stderr)
        return 1

    if not args.check:
        AGENTS_DIR.mkdir(parents=True, exist_ok=True)

    written = 0
    for code, skill_dir, agent in agents:
        content = _render(code, skill_dir, agent)
        out = AGENTS_DIR / f"{code}.md"
        label = f"{agent.get('icon','')} {agent.get('name')} ({agent.get('title')})"
        if args.check:
            exists = "exists" if out.is_file() else "MISSING"
            print(f"  [{exists}] {out.relative_to(REPO_ROOT)}  ←  {label}")
            continue
        out.write_text(content, encoding="utf-8")
        written += 1
        print(f"  ✓ {out.relative_to(REPO_ROOT)}  ←  {label}")

    if args.check:
        print(f"\n{len(agents)} BMAD agent(s) discovered.")
    else:
        print(f"\nGenerated {written} subagent definition(s) in {AGENTS_DIR.relative_to(REPO_ROOT)}/")
        print("Restart the session (or reload agents) for the Agent tool to pick them up.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
