// AUTO-GENERATED by 🦉 Noctua | 2026-03-08T19:57:46.850Z
// Reason: Provides the missing screen‑capture capability needed to fulfill the user's request
import type { ToolImplementation, ToolContext } from '../registry.js';
import screenshot from 'screenshot-desktop';
import { randomUUID } from 'node:crypto';
import { promises as fs } from 'node:fs';
import { join } from 'node:path';
import os from 'node:os';

const CaptureScreenshotTool: ToolImplementation = {
    definition: {
        name: 'capture_screenshot',
        description: 'Captures the current screen and returns the image as a base64‑encoded PNG',
        parameters: {
            "type": "object",
            "properties": {},
            "required": []
        },
    },
    async execute(_args: Record<string, unknown>, _context: ToolContext): Promise<string> {
        try {
            // Capture the screen as a Buffer (PNG format)
            const imgBuffer: Buffer = await screenshot({ format: 'png' });

            // Encode to base64 for transport
            const base64Image = imgBuffer.toString('base64');

            // Optionally write a temporary file for audit / debugging
            const tempDir = os.tmpdir();
            const tempPath = join(tempDir, `screenshot-${randomUUID()}.png`);
            await fs.writeFile(tempPath, imgBuffer);

            // Return a human‑readable message with the base64 data
            return `✅ Screenshot captured successfully.\nBase64 PNG (data URI): data:image/png;base64,${base64Image}\nTemporary file saved at: ${tempPath}`;
        } catch (err) {
            // Wrap any error with a descriptive message
            throw new Error(`Failed to capture screenshot: ${(err as Error).message}`);
        }
    },
};

export default CaptureScreenshotTool;