// AUTO-GENERATED by 🦉 Noctua | 2026-03-08T21:13:18.230Z
// Reason: Uses macOS screencapture command to take a screenshot and save it to a temporary file
import type { ToolImplementation, ToolContext } from '../registry.js';
import { exec } from 'node:child_process';
import { promisify } from 'node:util';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const execAsync = promisify(exec);

const CaptureScreenshotTool: ToolImplementation = {
    definition: {
        name: 'capture_screenshot',
        description: 'Captures a screenshot of the screen and returns the file path',
        parameters: {
        "type": "object",
        "properties": {},
        "required": []
},
    },
    async execute(args: Record<string, unknown>, context: ToolContext): Promise<string> {
        const tmpDir = tmpdir();
        const filePath = join(tmpDir, `screenshot_${Date.now()}.png`);
        
        try {
            await execAsync(`screencapture -x "${filePath}"`);
            return filePath;
        } catch (error) {
            throw new Error(`Failed to capture screenshot: ${(error as Error).message}`);
        }
    },
};

export default CaptureScreenshotTool;