version: 2
updates:
  - package-ecosystem: pip
    directory: "/v2"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        dependency-type: development
      production:
        dependency-type: production
